#ifndef DEF_H
#define DEF_H

#define HC_CMD "cmd"
#define HC_REG "reg"
#define HC_USERNAME "username"
#define HC_PASSWORD "password"
#define HC_OK "ok"
#define HC_RESULT "result"
#define HC_REASON "reason"
#define HC_ERR "err"
#define HC_LOGIN "login"
#define HC_LAT "lat"
#define HC_LNG "lng"
#define HC_TYPE "type"
#define HC_DRIVER "dirver"
#define HC_USER "user"
#define HC_UPDATEDRIVERPOS "updatepos"
#define HC_GEOHASH "geohash"
#define HC_UPDATEDRIVERSTATUS "updatestatus"
#define HC_STATUS "status"
#define HC_UPDATEUSERORDERSTATUS "updateorder"
#define HC_ORDERID "orderid"
#define HC_USERSTATUS "status"
#define HC_ORDERREQUEST "orderrequest"
#define HC_LATBEGIN "lat1"
#define HC_LNGBEGIN "lng1"
#define HC_LATEND "lat2"
#define HC_LNGEND "lng2"
#define HC_TEL "tel"
#define HC_UPDATEUSERPOS "updatepos"

#endif // DEF_H
